settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: greet-service
    path: .
    env:
      GRPC_SRV_ADDR: localhost:50051
      TLS: false
      SSL_CERT_PATH: ssl/server.crt
      SSL_KEY_PATH: ssl/server.pem
      SSL_CA_CERT_PATH: ssl/ca.crt
      PROMETHEUS_PORT: 2114
    commands:
      install:
        status: true
        method: go build -o build srv/server.go
      run:
        status: true
        method: ./build
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
